WITH H AS (
    SELECT  DAILY_FEE,
            HISTORY_ID,
            DATEDIFF(END_DATE, START_DATE) + 1 AS DAY
      FROM  CAR_RENTAL_COMPANY_CAR C
            JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
            ON C.CAR_ID = R.CAR_ID
     WHERE  CAR_TYPE = '트럭'
), D AS (
    SELECT  LEFT(DURATION_TYPE, INSTR(DURATION_TYPE, '일') - 1) AS D_T,
            100 - DISCOUNT_RATE AS RATE
      FROM  CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE  CAR_TYPE = '트럭'
)
SELECT  HISTORY_ID,
        CASE
            WHEN DAY >= 90 THEN DAILY_FEE * DAY * (SELECT RATE FROM D WHERE D_T = 90) / 100
            WHEN DAY >= 30 THEN DAILY_FEE * DAY * (SELECT RATE FROM D WHERE D_T = 30) / 100
            WHEN DAY >= 7 THEN DAILY_FEE * DAY * (SELECT RATE FROM D WHERE D_T = 7) / 100
            ELSE DAILY_FEE * DAY
        END AS FEE
  FROM  H
 ORDER
    BY  FEE DESC,
        HISTORY_ID DESC
;

