SELECT  MONTH(START_DATE) AS MONTH
        , CAR_ID
        , COUNT(*) AS RECORDS
  FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C1
 WHERE  EXISTS (
        SELECT  1
          FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C2
         WHERE  1=1
                AND C1.CAR_ID = C2.CAR_ID
                AND C2.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
         GROUP
            BY  CAR_ID
        HAVING  COUNT(*) >= 5
        )
        AND C1.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
 GROUP
    BY    MONTH(START_DATE)
        , CAR_ID
 ORDER
    BY    MONTH(START_DATE)
        , CAR_ID DESC
;

# 2 5 7 8