SELECT  YEAR,
        M - SIZE_OF_COLONY AS YEAR_DEV,
        ID
  FROM  ECOLI_DATA E1 JOIN
        (
            SELECT  MAX(SIZE_OF_COLONY) AS M,
                    YEAR(DIFFERENTIATION_DATE) AS YEAR
              FROM  ECOLI_DATA E2
             GROUP
                BY  YEAR(DIFFERENTIATION_DATE)
        ) MAX_VAL
        ON YEAR(E1.DIFFERENTIATION_DATE) = MAX_VAL.YEAR
 ORDER
    BY  YEAR, YEAR_DEV
;