SELECT
      YEAR(ED.DIFFERENTIATION_DATE) AS YEAR
    , M - SIZE_OF_COLONY AS YEAR_DEV
    , ID
FROM
    ECOLI_DATA AS ED JOIN
    (SELECT MAX(SIZE_OF_COLONY) AS M, YEAR(DIFFERENTIATION_DATE) AS YEAR
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS MAX_OF_YEAR
    ON YEAR(ED.DIFFERENTIATION_DATE) = MAX_OF_YEAR.YEAR
ORDER BY
      YEAR
    , YEAR_DEV
;