SELECT
    DISTINCT(C.CAR_ID)
FROM
    CAR_RENTAL_COMPANY_CAR C JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY R ON
    C.CAR_ID = R.CAR_ID
WHERE
        CAR_TYPE = '세단'
    AND START_DATE >= '2022-10-01'
ORDER BY
    CAR_ID DESC