SELECT  ID,
        FISH_NAME,
        LENGTH
  FROM  (
        SELECT  FISH_TYPE, MAX(LENGTH) AS LEN
          FROM  FISH_INFO
         GROUP
            BY  FISH_TYPE
        ) FI JOIN FISH_INFO F
        ON 1=1
        AND FI.FISH_TYPE = F.FISH_TYPE
        AND LENGTH = LEN
        JOIN FISH_NAME_INFO FNI
        ON FI.FISH_TYPE = FNI.FISH_TYPE
 ORDER
    BY  ID
;