-- 코드를 입력하세요
SELECT
    INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM
    ICECREAM_INFO as ii
    JOIN FIRST_HALF as fh
    ON ii.flavor = fh.flavor
GROUP BY
    INGREDIENT_TYPE
ORDER BY
    TOTAL_ORDER